In [2]:
# HDR Image들의 평균을 계산해서 Silhouette Image 만드는 프로그램
import matplotlib as plt
import rawpy
import PIL
import os
import numpy as np
import matplotlib.pyplot as plt
import scipy as sci

def getfilelist(fname):
    path = "./"+fname+"/"
    file_list = os.listdir(path)
    ret = []
    for i in range(len(file_list)):
        Num = len(file_list[i])
        if Num > 4 and (file_list[i][-4:Num] == ".jpg" or file_list[i][-4:Num] == ".png"):
            ret.append([path,file_list[i]])
    return ret

def OpenImage(image):
    img = PIL.Image.open(image[0]+image[1])
    RGB = np.array(img)
    return (img, RGB)

def CloseImage(handle):
    handle[0].close()

os.makedirs("Output", exist_ok=True) # Result Images
Image_list = getfilelist("Input")
Cnt = 0
N = len(Image_list)
Silhouette =[]
Image_handle = []
print("HDR Images : {:d} Images are Loaded.".format(N))
for i, v in enumerate(Image_list):
    Image_handle.append(OpenImage(v))
    if Cnt == 0:
        Silhouette = Image_handle[i][1].astype('int32')
    else:
        Silhouette = np.add(Silhouette,Image_handle[i][1],dtype=np.int32)
    Cnt += 1
    print("{} processed.".format(v[1]))
    CloseImage(Image_handle[i])

Silhouette //= Cnt
Silhouette = np.clip(Silhouette, 0, 255).astype('uint8')
PIL.Image.fromarray(Silhouette).save("./Output/Silhouette.png")
print("Silhouette Mask Image ({}) is Processed.".format("Silhouette.png"))


HDR Images : 144 Images are Loaded.
000.jpg processed.
001.jpg processed.
002.jpg processed.
003.jpg processed.
004.jpg processed.
005.jpg processed.
006.jpg processed.
007.jpg processed.
008.jpg processed.
009.jpg processed.
010.jpg processed.
011.jpg processed.
012.jpg processed.
013.jpg processed.
014.jpg processed.
015.jpg processed.
016.jpg processed.
017.jpg processed.
018.jpg processed.
019.jpg processed.
020.jpg processed.
021.jpg processed.
022.jpg processed.
023.jpg processed.
024.jpg processed.
025.jpg processed.
026.jpg processed.
027.jpg processed.
028.jpg processed.
029.jpg processed.
030.jpg processed.
031.jpg processed.
032.jpg processed.
033.jpg processed.
034.jpg processed.
035.jpg processed.
036.jpg processed.
037.jpg processed.
038.jpg processed.
039.jpg processed.
040.jpg processed.
041.jpg processed.
042.jpg processed.
043.jpg processed.
044.jpg processed.
045.jpg processed.
046.jpg processed.
047.jpg processed.
048.jpg processed.
049.jpg processed.
050.jpg proces

In [3]:
# monitor_pixels_h#w#.npy 생성 코드 (단위 : m)
import numpy as np

monitor = np.load('./monitor_pixels_h12w6_2.npy')
print(monitor.shape)
print((monitor*1000).astype('int32'))

# 카메라 위치 = (0,0,0)
# start (pattern000.png 기준) = [7*(X-4),13+7*Y,0] (16x9), [13*(X-2),15.5+13*Y,0] (9x5), [21.5*(X-1),12.75+21.5*Y,0] (6x3) [mm]
# [11*(X-2.5),7.5+11*Y,0] (12x6), [8*(X-3.5),6+8*Y,0] (16x8) [mm]
# superpixel(정사각형) 한 변의 길이 = 7mm (16x9), 13mm (9x5), 21.5mm (6x3), 11mm (12x6), 8mm (16x8), z = 0 고정(평면)

width = 6 # light_C
height = 12 # light_R
monitor =[[[0.0]*3 for _ in range(width)] for _ in range(height)]
for i in range(height):
    for j in range(width):
        monitor[i][j][0] = 0.011*(j-2.5) # X
        monitor[i][j][1] = 0.0075 + 0.011*(i) # Y
monitor = np.array(monitor).astype('float32')

np.save(f'./monitor_pixels_h{height}w{width}.npy', monitor)
print("monitor_pixels_h"+str(height)+"w"+str(width)+".npy is saved. {}\n".format(monitor.shape))
print(monitor)



(12, 6, 3)
[[[-27   5   0]
  [-16   5   0]
  [ -5   5   0]
  [  5   5   0]
  [ 16   5   0]
  [ 27   5   0]]

 [[-27  16   0]
  [-16  16   0]
  [ -5  16   0]
  [  5  16   0]
  [ 16  16   0]
  [ 27  16   0]]

 [[-27  27   0]
  [-16  27   0]
  [ -5  27   0]
  [  5  27   0]
  [ 16  27   0]
  [ 27  27   0]]

 [[-27  38   0]
  [-16  38   0]
  [ -5  38   0]
  [  5  38   0]
  [ 16  38   0]
  [ 27  38   0]]

 [[-27  49   0]
  [-16  49   0]
  [ -5  49   0]
  [  5  49   0]
  [ 16  49   0]
  [ 27  49   0]]

 [[-27  60   0]
  [-16  60   0]
  [ -5  60   0]
  [  5  60   0]
  [ 16  60   0]
  [ 27  60   0]]

 [[-27  71   0]
  [-16  71   0]
  [ -5  71   0]
  [  5  71   0]
  [ 16  71   0]
  [ 27  71   0]]

 [[-27  82   0]
  [-16  82   0]
  [ -5  82   0]
  [  5  82   0]
  [ 16  82   0]
  [ 27  82   0]]

 [[-27  93   0]
  [-16  93   0]
  [ -5  93   0]
  [  5  93   0]
  [ 16  93   0]
  [ 27  93   0]]

 [[-27 104   0]
  [-16 104   0]
  [ -5 104   0]
  [  5 104   0]
  [ 16 104   0]
  [ 27 104   0]]

 [[-27 11

In [17]:
import matplotlib as plt
import rawpy
import PIL
import os
import numpy as np
import matplotlib.pyplot as plt
import scipy as sci
import cv2
from PIL import Image

def getfilelist(fname):
    path = "./"+fname+"/"
    file_list = os.listdir(path)
    ret = []
    for i in range(len(file_list)):
        Num = len(file_list[i])
        if Num > 4 and (file_list[i][-4:Num] == ".jpg" or file_list[i][-4:Num] == ".png"):
            ret.append([path,file_list[i]])
    return ret

def OpenImage(image):
    img = cv2.imread(image[0]+image[1],cv2.IMREAD_COLOR)
    return img

def CloseImage(handle):
    handle[0].close()

os.makedirs("Output", exist_ok=True) # Result Images
Image_list = getfilelist("20240820_155625_out")
Cnt = 0
N = len(Image_list)
print("HDR Images : {:d} Images are Loaded.".format(N))
for i, v in enumerate(Image_list):
    Image_handle = OpenImage(v)
    dstG = cv2.cvtColor(cv2.GaussianBlur(Image_handle,(0,0),1), cv2.COLOR_BGR2RGB)
    dstG *= 1
    Image.fromarray(dstG).save('./Output/'+v[1],'PNG')
    print("{} processed.".format(v[1]))
    Cnt += 1
print(f"Total {Cnt} Images are Processed.")


HDR Images : 144 Images are Loaded.
000.png processed.
001.png processed.
002.png processed.
003.png processed.
004.png processed.
005.png processed.
006.png processed.
007.png processed.
008.png processed.
009.png processed.
010.png processed.
011.png processed.
012.png processed.
013.png processed.
014.png processed.
015.png processed.
016.png processed.
017.png processed.
018.png processed.
019.png processed.
020.png processed.
021.png processed.
022.png processed.
023.png processed.
024.png processed.
025.png processed.
026.png processed.
027.png processed.
028.png processed.
029.png processed.
030.png processed.
031.png processed.
032.png processed.
033.png processed.
034.png processed.
035.png processed.
036.png processed.
037.png processed.
038.png processed.
039.png processed.
040.png processed.
041.png processed.
042.png processed.
043.png processed.
044.png processed.
045.png processed.
046.png processed.
047.png processed.
048.png processed.
049.png processed.
050.png proces